# Generated by Django 5.1.1 on 2025-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('card_online', 'Картой онлайн'), ('card_on_delivery', 'Картой при получении')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('delivered', 'Доставлено'), ('cancelled', 'Отменен')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
